Handling for constraint violation error from PK vs UK (#2714)
Unique Constraint violation check response from voyager is based on the on primary key conflict mode
  ERROR: All errors whether due to Primary Key or Unique Key, should be non retryable and error out
  IGNORE: If the error is due to Primary Key conflict only then ignore it since user has selected that mode. Otherwise for unique key case it will non retry and error.

Moreover the overall check for violation is much more strict now.
i.e. when ignoring we check the expected primary key constraint name in the error msg

Syntax: violates unique constraint "%s"
Here we check with the specific primary key constraint name that is expected for that batch